[package]
name = "speedy"
version = "0.1.0"
authors = ["Matthew Planchard <msplanchard@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.32.0"
lazy_static = "~1.3.0"
liquid = "~0.18.2"
warp = "~0.1.12"
