[package]
name = "speedy"
version = "0.1.0"
authors = ["Matthew Planchard <msplanchard@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
diesel = { version = "1.0.0", features = ["sqlite"] }
diesel_migrations = "1.4.0"
rocket = "0.4.0"
rocket_contrib = "0.4.0"
