[package]
name = "speedy"
version = "0.1.0"
authors = ["Matthew Planchard <msplanchard@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.32.0"
diesel = { version = "~1.0.0", features = ["sqlite"] }
lazy_static = "~1.3.0"
tera = "~0.11.20"
warp = "~0.1.12"
