[package]
name = "speedy"
version = "0.1.0"
authors = ["Matthew Planchard <msplanchard@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "~0.4.6"
clap = "~2.33.0"
liquid = "~0.19.0"
pulldown-cmark = "~0.8.0"
warp = "~0.1.12"
